Add caching to navigation and snippet controller
sulu/SuluHeadlessBundle pull request #112
Opened 2022-06-09 12:29 UTC by Prokyonn

Add caching and tag invalidation support for `NavigationController` and `SnippetAreaController`

2022-06-09 12:36 UTC, alexander-schranz requested changes
Missing a subscriber which invalidates snippet areas.

2022-06-09 12:36 UTC, alexander-schranz commented on Controller/NavigationController.php
> +    public const NAVIGATION_CACHE_LIFE_TIME = '604800';
Should be configureable.

2022-06-09 12:36 UTC, alexander-schranz commented on Controller/NavigationController.php
> +        $response->setSharedMaxAge(0);
Should be the values from: https://github.com/sulu/sulu/blob/75578fc6074db7f31d63eb4e958b1e6aac676423/src/Sulu/Bundle/HttpCacheBundle/CacheLifetime/CacheLifetimeEnhancer.php#L77-L78

2022-06-09 12:36 UTC, alexander-schranz commented on Controller/SnippetAreaController.php
> +    public const SNIPPET_AREA_CACHE_LIFE_TIME = '604800';
Should be configureable.

2022-06-09 12:36 UTC, alexander-schranz commented on Controller/SnippetAreaController.php
> +        $response->setSharedMaxAge(0);
Should be the values from: https://github.com/sulu/sulu/blob/75578fc6074db7f31d63eb4e958b1e6aac676423/src/Sulu/Bundle/HttpCacheBundle/CacheLifetime/CacheLifetimeEnhancer.php#L77-L78

2022-06-09 12:36 UTC, alexander-schranz commented on EventSubscriber/NavigationInvalidationSubscriber.php
> +class NavigationInvalidationSubscriber implements EventSubscriberInterface
```suggestion
/**
 * @final
 * @internal
 */
class NavigationInvalidationSubscriber implements EventSubscriberInterface
```

Should be kept internal and final.

2022-06-09 12:38 UTC, alexander-schranz commented on EventSubscriber/NavigationInvalidationSubscriber.php
> +            Events::REMOVE_LOCALE => ['invalidateNavigationContextBeforeRemovingLocale', 8192],
This listeners should just collect the data.

And a `Flush` subscriber with alow priority shoudl then call the CacheManager.

Do not forget to implement kernel.reset event to empty the array and empty the array.

2022-06-09 13:54 UTC, Prokyonn commented
> Missing a subscriber which invalidates snippet areas.

@alexander-schranz do we really need one?

At the moment it is working, as soon as the snippet is modified, the tag is invalidated through the default [InvalidationSubscriber](https://github.com/sulu/sulu/blob/2.5/src/Sulu/Bundle/HttpCacheBundle/EventSubscriber/InvalidationSubscriber.php#L126) from the HttpCacheBundle

2022-06-09 13:59 UTC, alexander-schranz commented
@Prokyonn but if a default snippet is changed to another default snippet the cache need to be invalided also. Else you will get a long time the old default snippet.

2022-06-10 08:15 UTC, alexander-schranz commented on EventSubscriber/NavigationInvalidationSubscriber.php
> +class NavigationInvalidationSubscriber implements EventSubscriberInterface
would add the `ResetInterface` here.

2022-06-10 08:38 UTC, alexander-schranz approved these changes

2022-06-10 08:38 UTC, merged