Add extension placeholder for serialized medias
sulu/SuluHeadlessBundle pull request #127
Opened 2023-02-20 22:50 UTC by Prokyonn

2023-02-20 23:10 UTC, Prokyonn commented
@alexander-schranz @wachterjohannes  to prevent the BC break, we could maybe add a config like this:

```yaml
sulu_headless:
    media:
        use_preferred_extension: true
```

WDYT?

2023-02-20 23:17 UTC, alexander-schranz requested changes

2023-02-20 23:17 UTC, alexander-schranz commented on Content/Serializer/MediaSerializer.php
> +            $mediaData['preferredExtension'] = $preferredExtension;
```suggestion
            $mediaData['formatPreferredExtension'] = $preferredExtension;
```

2023-02-20 23:17 UTC, alexander-schranz commented on Content/Serializer/MediaSerializer.php
>          if ($preferredExtension) {
I think `formatUri`, `formatPreferredExtension` should be `null` if there is no preferredExtension as I think that indicates that there are no formats available for this media. E.g. `.doc`, `.xls`, ...

2023-02-20 23:17 UTC, alexander-schranz commented on Content/Serializer/MediaSerializer.php
> +        $fileName = \pathinfo($fileName)['filename'] . '.' . 'extension';
```suggestion
        $fileName = \pathinfo($fileName)['filename'] . '.' . '{extension}';
```

2023-02-20 23:17 UTC, alexander-schranz commented on Tests/Functional/Controller/responses/navigation__get_excerpt.json
> +                            "preferredExtension": "png",
would replace `@string@` in `formatUri` to check the Uri is as expected.

2023-02-20 23:17 UTC, alexander-schranz commented on Tests/Unit/Content/Serializer/MediaSerializerTest.php
> +            ->willReturn('/media/1/{format}/media-1.extension?v=1-0')
Can we create a real instance of `LocalFormatCache` so we avoid this mock.

2023-02-20 23:22 UTC, alexander-schranz commented
@Prokyonn if somebody is using `^0.9` they will not get automatically `0.10`, as `^` in pre stable versions is handed like `0.9.*` so active update is required and so I'm fine with this bc break and no addional flag.

2023-02-20 23:23 UTC, alexander-schranz commented on UPGRADE.md
> +    "preferredExtension": "png"
```suggestion
    "formatUri": "/media/1/{format}/media-1.{extension}?v=1-0",
    "formatPreferredExtension": "png"
```

2023-02-21 07:20 UTC, wachterjohannes commented
> @alexander-schranz @wachterjohannes to prevent the BC break, we could maybe add a config like this:
> 
> ```yaml
> sulu_headless:
>     media:
>         use_preferred_extension: true
> ```
> 
> WDYT?

@Prokyonn would also go with a flag and throw a deprecation message when it is not set! else the PR LGTM.

2023-02-21 13:06 UTC, Prokyonn commented
as discussed internally, we'll omit the configuration BC layer, because of
> if somebody is using ^0.9 they will not get automatically 0.10, as ^ in pre stable versions is handled like 0.9.* so active update is required and so I'm fine with this bc break and no additional flag.

2023-02-21 13:38 UTC, alexander-schranz approved these changes

2023-02-21 13:44 UTC, alexander-schranz approved these changes

2023-02-21 13:48 UTC, merged