Add defaults to propertyMap in PageSelectionResolver
sulu/SuluHeadlessBundle pull request #55
Opened 2020-11-20 14:19 UTC by alexandersch

2020-11-23 08:45 UTC, nnatter reviewed
Would be great if you could adjust the test cases 🙂 

Also, I think we should add this to the `PageDataProviderResolver` too to keep thinks consistent

2020-11-23 08:48 UTC, alexandersch commented
I will look into that in a bit.

2020-11-23 17:14 UTC, alexander-schranz requested changes
You should not make the structureResolver nullable.
What you are currently missing is that the expected calls in the test need to be changed as ` is now called always with title and url.

So the:

```
$this->structureResolver->resolveProperties()
```

calls need to be adjusted in the [PageSelectionResolverTest](https://github.com/sulu/SuluHeadlessBundle/blob/1bea2a10d52a1b062311fabb067dee71a422bb91/Tests/Unit/Content/ContentTypeResolver/PageSelectionResolverTest.php#L127)

because all now have `title` and `url` in it. For example:

```diff
        $this->structureResolver->resolveProperties(
            $pageStructure1->reveal(),
            [
                'title' => 'title',
+                'url' => 'url',
                'excerptTitle' => 'excerpt.title',
                'categories' => 'excerpt.categories',
            ],
            'en'
        )->willReturn([
            'id' => 'page-id-1',
            'template' => 'default',
            'content' => [
                'title' => 'Page Title 1',
                'excerptTitle' => 'Page Excerpt Title 1',
            ],
            'view' => [
                'title' => [],
                'excerptTitle' => [],
            ],
        ]);
```

if you adjust this the tests should be again green.

2020-11-23 17:14 UTC, alexander-schranz commented on Content/StructureResolver.php
> +    ): ?array {
this should not be nullable

2020-11-23 17:14 UTC, alexander-schranz commented on Content/StructureResolverInterface.php
> +    ): ?array;
this should not be nullable

2020-11-25 13:08 UTC, alexander-schranz reviewed
@alexandersch I updated the tests for you. Now all should be fine. Thank you for your effort!

2020-11-25 13:59 UTC, nnatter approved these changes
Looks good - thanks a lot to both of you!

2020-11-25 13:59 UTC, merged