Added support for preview image in media serializer
sulu/SuluHeadlessBundle pull request #80
Opened 2021-03-26 15:37 UTC by alexandersch

I've added support for the preview image in MediaSerializer as it didn't respect preview images.

2021-03-26 15:43 UTC, alexander-schranz requested changes
@alexanderschr Thank you for the Pull Request 👍 . Would be nice to have a Unit test with a `PreviewImage` in https://github.com/sulu/SuluHeadlessBundle/blob/0.x/Tests/Unit/Content/Serializer/MediaSerializerTest.php. Let me know if you have time to add this else we can do it.

2021-03-26 15:43 UTC, alexander-schranz commented on Content/Serializer/MediaSerializer.php
> +            $formatMediaApi = new Media($media->getPreviewImage(), $locale);
Looks like there is currently a false typehint in the sulu core here so we can workaround this currently with:

```suggestion
        /** @var Media|null $previewImage */
        $previewImage = $media->getPreviewImage();
        if($previewImage) {
            $formatMediaApi = new Media($previewImage, $locale);
```

2021-03-26 15:47 UTC, alexander-schranz commented on Content/Serializer/MediaSerializer.php
> +        /** @var Media|null $previewImage */
Sorry my fault this need to be as it is not an api media instead the media entity:

```suggestion
        /** @var MediaInterface|null $previewImage */
```

2021-03-26 18:27 UTC, alexandersch commented
> @alexanderschr Thank you for the Pull Request 👍 . Would be nice to have a Unit test with a `PreviewImage` in https://github.com/sulu/SuluHeadlessBundle/blob/0.x/Tests/Unit/Content/Serializer/MediaSerializerTest.php. Let me know if you have time to add this else we can do it.

2021-03-26 23:03 UTC, alexander-schranz approved these changes

2021-03-26 23:04 UTC, merged

2021-03-26 23:04 UTC, alexander-schranz commented
@alexandersch Thank you! Good Work 👍

2021-03-29 07:36 UTC, nnatter commented
Thanks a lot for the PR - really appreciating this!